[plugin-next] Fix Rollup when no template in an SFC
vuejs/rollup-plugin-vue pull request #387
Opened 2020-09-09 02:16 UTC by elevatebart

Changes proposed in this pull request:
SFCs can have a script block only
In this case, the render function should not be replaced by the empty template function.
It should be left alone.

/ping @znck @jtommy

2020-09-09 06:02 UTC, jtommy commented
@elevatebart Yes, removing it seems to work as I tried manually but I don't know if it's really correct or not in the new Vue 3.

2020-09-16 20:12 UTC, jtommy commented on src/index.ts
> +  const templateImport = descriptor.template
The right condition is `!descriptor.template`

2020-09-16 20:13 UTC, jtommy requested changes

2020-09-16 20:13 UTC, jtommy commented on examples/no-template/src/HelloWorld.vue
> +import h from 'vue'
h isnt' the default export, you should use `import { h } from 'vue'`

2020-10-20 04:56 UTC, znck approved these changes

2020-10-20 05:15 UTC, merged

2020-10-22 17:00 UTC, meteorlxy commented
Some edge cases that may be related to https://github.com/vuejs/vue-next/issues/2463

2020-10-29 06:13 UTC, zouhangwithsweet commented
I am troubled by this question.
When will you release the new version, maybe beta.11 ?:clap: